# Generated by Django 4.2.7 on 2025-11-09 05:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('accuracy', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('last_trained', models.DateField()),
                ('data_sources', models.JSONField(default=list)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model Insight',
                'verbose_name_plural': 'AI Model Insights',
                'ordering': ['-last_trained'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True)),
                ('owner', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('Residential Property', 'Residential Property'), ('Commercial Building', 'Commercial Building'), ('Farm Land', 'Farm Land'), ('Industrial Facility', 'Industrial Facility'), ('Port', 'Port')], max_length=100)),
                ('location_name', models.CharField(max_length=200)),
                ('insured_value_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('policy_start_date', models.DateField()),
                ('policy_end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-insured_value_usd'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(max_length=50, unique=True)),
                ('policy_id', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=200)),
                ('disaster_type', models.CharField(choices=[('Flood', 'Flood'), ('Wildfire', 'Wildfire'), ('Storm', 'Storm'), ('Earthquake', 'Earthquake'), ('Drought', 'Drought')], max_length=50)),
                ('pre_image', models.ImageField(blank=True, null=True, upload_to='claims/pre/')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='claims/post/')),
                ('pre_image_url', models.URLField(blank=True, null=True)),
                ('post_image_url', models.URLField(blank=True, null=True)),
                ('damage_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('claim_amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('claim_status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('auto_approved', models.BooleanField(default=False)),
                ('date_filed', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insurance Claim',
                'verbose_name_plural': 'Insurance Claims',
                'ordering': ['-date_filed'],
            },
        ),
        migrations.CreateModel(
            name='ParametricTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_id', models.CharField(max_length=50, unique=True)),
                ('parameter', models.CharField(max_length=100)),
                ('threshold', models.FloatField()),
                ('current_value', models.FloatField()),
                ('triggered', models.BooleanField(default=False)),
                ('location_name', models.CharField(max_length=200)),
                ('date_checked', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parametric Trigger',
                'verbose_name_plural': 'Parametric Triggers',
                'ordering': ['-date_checked'],
            },
        ),
        migrations.CreateModel(
            name='RiskZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('flood_risk', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('wildfire_risk', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('storm_risk', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('vegetation_dryness', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('avg_temp_c', models.FloatField()),
                ('sea_level_rise_m', models.FloatField(default=0.0)),
                ('historical_events', models.IntegerField(default=0)),
                ('risk_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Risk Zone',
                'verbose_name_plural': 'Risk Zones',
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='DamageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('damage_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('affected_area_sqm', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('ai_model_used', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='api.insuranceclaim')),
            ],
            options={
                'verbose_name': 'Damage Analysis',
                'verbose_name_plural': 'Damage Analyses',
                'ordering': ['-analysis_date'],
            },
        ),
    ]
